### ISSUE TITLE
cascade doesn't see generated templates

### ISSUE THREAD

**Issue by vheathen** [sportradar/elixir-workspace#1]
Thanks a lot again for this project! Everything seems to work except `cascade`.

The log would explain everything:

```
❯ mix cascade template -- --name context
* creating templates/context/PLACEHOLDER.md
* creating lib/incomezee/templates/context.ex
❯ mix cascade.help context
** (Mix) No template `context` found. Run "mix cascade.help" to get a list of available templates
❯ mix cascade.help
The following templates are available:

  template  # Generates a new template

Run mix cascade NAME to generate code from the given template
Run mix cascade.help NAME to see help for a specific template
```

It looks like `Cascade.templates()` call from the mix task doesn't return anything but its own template, but if I run `iex -S mix` and do `Cascade.template()` manually - it actually shows the new `context` template.

**Comment by pnezis** [comment]
Where do you run this from? If you are running it from the workspace root it will not work since by default `elixirc_paths` are disabled.

**Comment by pnezis** [comment]
Managed to reproduce it, can you try again with latest git version?

**Comment by vheathen** [comment]
> If you are running it from the workspace root it will not work since by default elixirc_paths are disabled.

Yes, I understand that, and I added the generated lib path to the `elirixrc_paths`.

**Comment by vheathen** [comment]
> Managed to reproduce it, can you try again with latest git version?

Yes, now it shows the new template, thanks!

**Comment by pnezis** [comment]
> Yes, I understand that, and I added the generated lib path to the `elirixrc_paths`.

Alternatively you could create a `generators` package, add all your templates there, and add it as a path dependency to your workspace root so cascade works from the root folder as well.

**Comment by vheathen** [comment]
> > Yes, I understand that, and I added the generated lib path to the `elirixrc_paths`.
> 
> Alternatively you could create a `generators` package, add all your templates there, and add it as a path dependency to your workspace root so cascade works from the root folder as well.

This makes a lot of sense, thanks for the tip!
