### ISSUE TITLE
LSP Configuration

### ISSUE THREAD

**Issue by jprincipe** [sportradar/elixir-workspace#4]
Hey @pnezis thanks for your work on this.  I've been setting up my projects exactly the way you have described for years now and hadn't found a clean solution to manage them at the top level.  This is a great solution.

One question I had was how you handle LSP configuration.  Typically tools like ElixirLS only look for a `mix.exs` file as the top level of a project.  With my conversion to using Workspace that file now only contains the Workspace deps.

**Comment by pnezis** [comment]
Hi @jprincipe a rarely use an LSP, but if you check at the [elixir forum post about workspace](https://elixirforum.com/t/workspace-a-set-of-tools-for-working-with-elixir-monorepos/63536) you will find a relevant discussion. Hope this helps.

**Comment by pnezis** [comment]
Also check this relevant PR in `vscode-elixir-ls`: https://github.com/elixir-lsp/vscode-elixir-ls/pull/425
